### ISSUE TITLE
遇到问题求助

### ISSUE THREAD

**Issue by zhangxq9944** [zjunlp/KnowPrompt#1]
您好，我想问一下您几个问题：
1： virtual template words 指的是构造的模板吗？也就是图一中的
Hamilton [MASK] British [SEP]
2: answer words 指的是 [MASK] 预测的的关系词吗？ 图一中的 country,city,residence
3: 公式5中的 h,t,r 分别指的是什么？
4：文中多次提到 estimate the probability distributions ，这个值是怎么算的？

非常感谢

**Comment by njcx-ai** [comment]
您好：
1. virtual template words 指的[sub]Hamilton [sub]其中的[sub]，以避免歧义后更名叫virtual type words 
2.  是的
3. 公式5中的h, t, r为s, o, r (这里描述笔误未与前文对齐)
4. 根据pre-defined的类别算的，例如：per:birth_of_place.  per:birth_of_data， 对于[sub]，person: 1;   对于[sub]，place: 0.5, data: 0.5
