### ISSUE TITLE
关于预训练语言模型选择的问题

### ISSUE THREAD

**Issue by Real-bojack** [zjunlp/KnowPrompt#10]
请问一下作者，如果我想选择bert作为预训练模型，应该修改哪些参数？

**Comment by njcx-ai** [comment]
很抱歉当初实验时候只跑了roberta， 代码内没设置模型切换，若想选择bert作为预训练模型可能得改一下代码细节而不仅是输入参数。

**Comment by Real-bojack** [comment]
哦哦 谢谢！
