### ISSUE TITLE
experiment result

### ISSUE THREAD

**Issue by cpmss521** [zjunlp/KnowPrompt#12]
According to your introduction, I get experiment result on semeval dataset by  `bash scripts/semeval.sh `. but the loss is not dropping during training. where is wrong? I don't change anywhere. @njcx-ai 
![image](https://user-images.githubusercontent.com/47856948/188351324-ce5424bb-0167-45ea-b33b-489cc7b6ae59.png)

**Comment by njcx-ai** [comment]
We have never encountered this problem. Did you have the same environment configured as described in "requirements.txt"?
