### ISSUE TITLE
pytorch_lightning.utilities.exceptions.MisconfigurationException: No `test_dataloader()` method defined to run `Trainer.test`.

### ISSUE THREAD

**Issue by Lextra1999** [zjunlp/KnowPrompt#20]
![image](https://user-images.githubusercontent.com/61698443/231498853-94792ec0-9104-4f3e-9713-0455780d23fe.png)
The training works but it throws the exception.
**Environment**  pytorch_lightning ==1.5.0

**Comment by njcx-ai** [comment]
It may be an environment configuration problem. You can try to follow the same environment configured as described in "requirements.txt".
Thanks.
