### ISSUE TITLE
code

### ISSUE THREAD

**Issue by githubgtl** [zjunlp/KnowPrompt#21]
sorry to borther you,I have seen your paper and code, but I couldn't see any prompt method,I just see the relation between two entities have the different  #perfermence from trditional relation perfermence.Is there any unseen code published?

**Comment by njcx-ai** [comment]
Hi, thanks for your attention on our paper. This paper proposes prompts based on entity relationship constraints (shorter), rather than large prompt words. The specific prompt words are spliced together with the input, and the specific format is shown in Figure 2 in the paper.

**Comment by githubgtl** [comment]
yes,i see your figure 2 in your paper , but your code seems to encode the relation directly,there is no connection between sentence and your relation structure

**Comment by njcx-ai** [comment]
You can refer to https://github.com/zjunlp/KnowPrompt/blob/5f1ce468c33d9d8f4067a3edd70bbf810bc5fff4/lit_models/transformer.py#L167C38-L167C38

**Comment by githubgtl** [comment]
OK ,thank you for your help

**Comment by githubgtl** [comment]
OK ,thank you for your help

**Comment by githubgtl** [comment]
If i want to change the model to apply chinese, I only change the model path and dataset, Right?

**Comment by zxlzr** [comment]
Yes, if your label is Chinese, you may also change the to use a Chinese verberlizer, just change the label words.

**Comment by njcx-ai** [comment]
Some fixed English prompts in the code should also need to be modified.
