### ISSUE TITLE
configure_optimizers def

### ISSUE THREAD

**Issue by AmirLayegh** [zjunlp/KnowPrompt#22]
Hi, many thanks for providing the code. I have a question why do you have two configure_optimizers() in the Base lightning module? 
another question is that I know that the configure_optimizers function in the BertLitModel is for two-stage training but we do not need to check the optimizer_grouped_parameters in the training_step() and then optimize them?

**Comment by njcx-ai** [comment]
Hi, thanks for your interest in our paper. We are sorry that the first configure_optimizers() should be commented out. That means that only the second configure_optimizers() works. In addition, for the second question, we don't need to check the optimizer_grouped_parameters in the training_step().
