### ISSUE TITLE
跑代码报错：ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

### ISSUE THREAD

**Issue by yangqianBLCU** [zjunlp/KnowPrompt#24]
<img width="1112" alt="截屏2023-10-18 15 23 07" src="https://github.com/zjunlp/KnowPrompt/assets/93829491/25673a7b-7c57-4a04-8785-837b04b60df4">
而且已经把reberta-large模型下载到本地，也更改了main.py中的from_pretrain()的地址，还是报错

**Comment by zxlzr** [comment]
您好看报错是您的网络问题模型没下载成功，建议您可以先把模型下载本地再重试一下。

**Comment by yangqianBLCU** [comment]
> 您好看报错是您的网络问题模型没下载成功，建议您可以先把模型下载本地再重试一下。

而且已经把reberta-large模型下载到本地，也更改了main.py中的from_pretrain()的地址，还是报错

**Comment by yangqianBLCU** [comment]
<img width="1404" alt="截屏2023-10-18 15 40 44" src="https://github.com/zjunlp/KnowPrompt/assets/93829491/91f70bc9-670f-431a-98cc-5d1266593c43">
<img width="633" alt="截屏2023-10-18 15 41 25" src="https://github.com/zjunlp/KnowPrompt/assets/93829491/67a6c420-d316-4b8b-a2ea-7e3f24b1ef42">
已经进行下载模型到本地和改地址操作，还是没有解决问题，请问有什么好的方法吗？
谢谢

**Comment by youdianwangya** [comment]
你好，请问这个问题解决了吗？

**Comment by youdianwangya** [comment]
> <img alt="截屏2023-10-18 15 40 44" width="1404" src="https://private-user-images.githubusercontent.com/93829491/276149990-91f70bc9-670f-431a-98cc-5d1266593c43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzg3MDksIm5iZiI6MTcyMDE3ODQwOSwicGF0aCI6Ii85MzgyOTQ5MS8yNzYxNDk5OTAtOTFmNzBiYzktNjcwZi00MzFhLTk4Y2MtNWQxMjY2NTkzYzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDExMjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNDdmNTM4ZjgxODZmNGQ5OWRlYWQxOTcyMWI2MTYxZDg5MTgxZTFkNmY1ZmU0OGYxNGQ4OTYzZGRkZWY3NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDEtS_Noi9mquM82fWhEudy87rnat5186nbLvDg7KvU"> <img alt="截屏2023-10-18 15 41 25" width="633" src="https://private-user-images.githubusercontent.com/93829491/276150275-67a6c420-d316-4b8b-a2ea-7e3f24b1ef42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNzg3MDksIm5iZiI6MTcyMDE3ODQwOSwicGF0aCI6Ii85MzgyOTQ5MS8yNzYxNTAyNzUtNjdhNmM0MjAtZDMxNi00YjhiLWEyZWEtN2UzZjI0YjFlZjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDExMjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzY2I5N2Y5NmI0ODlhZTEzYzgzYzhmMWJhZWY4ZTAzNWE0MTJlYmU0YWViYTY2Mjc5OWE2NDE2MTY2MzlmMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TZTfNDX_kUdB8AOvQfs7V7jIqoC0p7xC7Nrqsps1wlE"> 已经进行下载模型到本地和改地址操作，还是没有解决问题，请问有什么好的方法吗？ 谢谢

你好，请问这个问题你解决了吗？迫切期待你的回复，谢谢

**Comment by yangqianBLCU** [comment]
我记得我当时就是下载到本地加载这样

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月05日 19:23 |
| 收件人 | zjunlp/KnowPrompt ***@***.***> |
| 抄送人 | yangqian ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [zjunlp/KnowPrompt] 跑代码报错：ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on. (Issue #24) |

已经进行下载模型到本地和改地址操作，还是没有解决问题，请问有什么好的方法吗？ 谢谢

你好，请问这个问题你解决了吗？迫切期待你的回复，谢谢

**Comment by youdianwangya** [comment]
> 我记得我当时就是下载到本地加载这样
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年07月05日 19:23 | | 收件人 | zjunlp/KnowPrompt ***@***.***> | | 抄送人 | yangqian ***@***.***>, Comment ***@***.***> | | 主题 | Re: [zjunlp/KnowPrompt] 跑代码报错：ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on. (Issue #24) | 已经进行下载模型到本地和改地址操作，还是没有解决问题，请问有什么好的方法吗？ 谢谢 你好，请问这个问题你解决了吗？迫切期待你的回复，谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>



> 我记得我当时就是下载到本地加载这样
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年07月05日 19:23 | | 收件人 | zjunlp/KnowPrompt ***@***.***> | | 抄送人 | yangqian ***@***.***>, Comment ***@***.***> | | 主题 | Re: [zjunlp/KnowPrompt] 跑代码报错：ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on. (Issue #24) | 已经进行下载模型到本地和改地址操作，还是没有解决问题，请问有什么好的方法吗？ 谢谢 你好，请问这个问题你解决了吗？迫切期待你的回复，谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

那请问解决了这个问题了吗

**Comment by youdianwangya** [comment]
> 我记得我当时就是下载到本地加载这样
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年07月05日 19:23 | | 收件人 | zjunlp/KnowPrompt ***@***.***> | | 抄送人 | yangqian ***@***.***>, Comment ***@***.***> | | 主题 | Re: [zjunlp/KnowPrompt] 跑代码报错：ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on. (Issue #24) | 已经进行下载模型到本地和改地址操作，还是没有解决问题，请问有什么好的方法吗？ 谢谢 你好，请问这个问题你解决了吗？迫切期待你的回复，谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

你好，请问你解决了这个问题了吗 期待你的回复
