### ISSUE TITLE
下载模型到本地后代码仍然报错：在main.py中更改了地址，仍然报错

### ISSUE THREAD

**Issue by yangqianBLCU** [zjunlp/KnowPrompt#25]
<img width="1404" alt="276149990-91f70bc9-670f-431a-98cc-5d1266593c43" src="https://github.com/zjunlp/KnowPrompt/assets/93829491/65c782bb-e340-498c-90d4-038d0f4f08be">
<img width="633" alt="276150275-67a6c420-d316-4b8b-a2ea-7e3f24b1ef42" src="https://github.com/zjunlp/KnowPrompt/assets/93829491/d942c66c-6147-47ec-9b16-741b915228c6">
<img width="1112" alt="276142022-25673a7b-7c57-4a04-8785-837b04b60df4" src="https://github.com/zjunlp/KnowPrompt/assets/93829491/7bbc05a0-250b-4184-9314-3d18ef49c1b2">

**Comment by njcx-ai** [comment]
您好，这个报错内容应该是加载模型的缓存文件的时候网络联接问题，建议您可以检查下本地存储路径下的模型文件是否完整呢

**Comment by yangqianBLCU** [comment]
ok,解决了，谢谢

**Comment by mxq15** [comment]
> 您好，这个报错内容应该是加载模型的缓存文件的时候网络联接问题，建议您可以检查下本地存储路径下的模型文件是否完整呢
您好，我也是这个问题，本地模型也是完整的，但就是无法继续

**Comment by mxq15** [comment]
> ok,解决了，谢谢

你好，可以问下你是如何解决的吗
