### ISSUE TITLE
python3.8 version is not compatible with pytorch1.8.1+cu111

### ISSUE THREAD

**Issue by vinland100** [zjunlp/KnowPrompt#27]
when i run `pip install -r requirments`,  show me this:

![image](https://github.com/zjunlp/KnowPrompt/assets/85446046/1de2f7ca-887d-4f52-8390-9553c456760b)

actually, this was only the first problem I had when I ran this codebase, and there were often configuration dependencies file errors during the run, and I didn't complete this experimental verification in the end

**Comment by zxlzr** [comment]
We have re-installed the requirements  and we could not reproduce your problem, maybe you can change another server/computer with a new environment, and try again. I think this may caused by the driver update of cuda and pytorch.

**Comment by njcx-ai** [comment]
Thanks for your attention. After all, this is the project code from three years ago. The version of the pytorch is constantly updated and iterated. Maybe the old versions like pytorch1.8.1 have been eliminated. It is recommended that you try it with python3.9 or install a higher version of torch.

**Comment by zxlzr** [comment]
Hi buddy, have you solved your issue? maybe you can also try in a new environment.
