### ISSUE TITLE
.ckpt  FileNotFoundError

### ISSUE THREAD

**Issue by Goye-Cassini** [zjunlp/KnowPrompt#28]
尝试了几个数据集，都是在最后两个epoch时报错：FileNotFoundError: [Errno 2] No such file or directory: '/home/code/KnowPrompt/output/epoch=2-Eval/f1=0.906.ckpt'，求指点

**Comment by njcx-ai** [comment]
您好，非常感谢您对我们工作的关注。这里可能是您创建类似“epoch=2-Eval”这样文件目录的名称与训练的epoch数值未同步，建议您排查一下变量定义和磁盘空间。

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by Goye-Cassini** [comment]
还没有

**Comment by zxlzr** [comment]
建议您手动检查下路径是否存在或检查下权限磁盘空间。

**Comment by Goye-Cassini** [comment]
路径是存在的，路径下也保存的有ckpt文件，只是保存的ckpt文件名和要找的ckpt文件名不一致

**Comment by njcx-ai** [comment]
可以试试debug模式跳过前面n-2个epoch, 看看最后2个epoch保存ckpt时发生了啥bug

**Comment by zxlzr** [comment]
请问您的问题解决了吗
