### ISSUE TITLE
what is the difference between virtual type words and soft prompt

### ISSUE THREAD

**Issue by lihuiliullh** [zjunlp/KnowPrompt#29]
It seems that the virtual type words and soft prompt are the same thing, except that virtual type words are initialized according to the prior probability distribution. 
May I know whether my understanding is correct?

**Comment by njcx-ai** [comment]
Thank you for your interest in KnowPrompt. Your understanding is correct; virtual type words are indeed implemented using soft prompts. In addition to being initialized according to the prior probability distribution, virtual type words also serve as typer markers in relation extraction tasks.

**Comment by yccckid** [comment]
how the prior probability is conducted in your code? is it the mean by torch.mean? Thank you!
