### ISSUE TITLE
About the calculation of \phi(r)

### ISSUE THREAD

**Issue by Frankie123421** [zjunlp/KnowPrompt#3]
hi, congratulations on your great work! 
I have a question after reading the paper (though I have not read the code yet). How do you calculate the value of \phi(r)? It seems that you don't explain that in the paper. Thank you.

**Comment by njcx-ai** [comment]
Hi, 
Thanks for your concern. We have introduced  𝜙𝑟 in the paper as "Furthermore, we adopt the weighted average function for 𝜙𝑟 to average embeddings of each words among C𝑟 to initialize these relation embeddings"
