### ISSUE TITLE
How relation embedding was constructed in the algorithm?

### ISSUE THREAD

**Issue by yccckid** [zjunlp/KnowPrompt#32]
I want to know how the relation embedding was constructed? I learned from this repo where relation embedding was built from the bert 【mask】? But this is the same to type word embedding. Am I right?

**Comment by njcx-ai** [comment]
Thank you for your interest in our work. To clarify, the relation embeddings are constructed at the vocabulary level of BERT. We perform relation classification by calculating the similarity between the model's output at the [MASK] position and the relation embeddings. I hope this explanation addresses your question.

**Comment by zxlzr** [comment]
hi buddy, do you have any further questions?

**Comment by yccckid** [comment]
Thank you for your kindness. I am still confused by the construction of the virtual answer words. one specific question is needed to be clarified.
(1) In the paper, you guys mentioned the MLM head was expanded with the relation embedding head (see Fig. 2), and there is a dot-product, right? So I want to know that how this process is conducted by your code? What is the relation embedding head, and where does it come from? Thank you guys!
